### PR TITLE
Type __new__ instead of adding __init__

### PR DESCRIPTION
**Pull request by aucampia**
I'm fairly sure adding __init__ changes runtime behaviour somewhat and it also is not needed, __new__ should be typed.

### CODE REVIEW

**Comment by aucampia** [comment]
rebasing now

**Comment by aucampia** [comment]
rebased

**Comment by aucampia** [comment]
Note: this will not pass PR validation without: https://github.com/ajnelson-nist/rdflib/pull/8

**Comment by aucampia** [comment]
Just ping me for a rebase

**Comment by ajnelson-nist** [comment]
I was reviewing this offline, and it looked good to merge to me.  Sorry for triggering the rebase need, I misunderstood your earlier comments about merging your changes and just went straight to the `master` branch.  I'm looking over these PRs now.

FWIW, I tend to not rebase, I'm comfortable with doing catch-up merges for review.

**Comment by ajnelson-nist** [comment]
But, I'll look at #8, thanks for the ordering tip.

**Comment by aucampia** [comment]
rebased again, CI should pass now.

**Comment by aucampia** [comment]
Okay fixing the issue with literal.

**Comment by ajnelson-nist** [comment]
Aye, I saw a missing `-> None` when I was reviewing.  Fortunately, minor matter.

**Comment by ajnelson-nist** [comment]
I saw some minor nits from `black`, I can pick those up in a follow-on patch.  Thanks!

**Pull request merged**
